version: '2.1'
services:
  config-server:
    build: config-server
    ports:
      - 9099:9099

  registry-service:
    build: registry-service
    ports:
      - 8990:8990

  api-gateway-service:
    build: api-gateway-service
    ports:
      - 8000:8000

  rabbitmq:
    ports:
      - 5672:5672

  auth-service:
    build: auth-service
    ports:
      - 8991:8991

  account-service:
    build: account-service
    ports:
      - 8992:8992

  catalog-service:
    build: catalog-service
    ports:
      - 8993:8993

  monitoring-service:
    build: monitoring-service
    ports:
      - 8080:8080

  order-service:
    build: order-service
    ports:
      - 8994:8994

  processing-service:
    build: processing-service
    ports:
      - 8999:8999