hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8990/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8991/oauth/token/user/current

spring:
  rabbitmq:
    host: localhost
