security:
  oauth2:
    client:
      clientId: catalog-service
      clientSecret: ${CATALOG_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:8991/oauth/token
      grant-type: client_credentials
      scope: backend

server:
  port: 8993

spring:
  datasource:
    url: jdbc:postgresql://catalog-service.cp7sfpktwiz7.eu-central-1.rds.amazonaws.com/catalogdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
