security:
  oauth2:
    client:
      clientId: order-service
      clientSecret: ${ORDER_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:8991/oauth/token
      grant-type: client_credentials
      scope: backend

server:
  port: 8994

spring:
  datasource:
    url: jdbc:postgresql://order-service.cp7sfpktwiz7.eu-central-1.rds.amazonaws.com/orderdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
