server:
  port: 9099

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services
  profiles:
    active: native
  security:
    user:
      password: ${CONFIG_SERVER_PASSWORD}
      name: ${CONFIG_SERVER_USER_NAME}
